// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAyuO3vNlf4uYoDHSGxKS3Pre1ShqZ6bhI',
    appId: '1:873539215769:web:8e427df758f91287653308',
    messagingSenderId: '873539215769',
    projectId: 'aswack-86a20',
    authDomain: 'aswack-86a20.firebaseapp.com',
    storageBucket: 'aswack-86a20.appspot.com',
    measurementId: 'G-WR0C1617K8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAESHOJixMslInnkgWZUgbvg9loxhRNi6c',
    appId: '1:873539215769:android:4b63ec66bf39105a653308',
    messagingSenderId: '873539215769',
    projectId: 'aswack-86a20',
    storageBucket: 'aswack-86a20.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQ7WNwFAiHtbkSInxTMI-gvbafK3SrQoY',
    appId: '1:873539215769:ios:3ffc28ab8a0e44ba653308',
    messagingSenderId: '873539215769',
    projectId: 'aswack-86a20',
    storageBucket: 'aswack-86a20.appspot.com',
    iosBundleId: 'com.example.zaroooriUser',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQ7WNwFAiHtbkSInxTMI-gvbafK3SrQoY',
    appId: '1:873539215769:ios:3ffc28ab8a0e44ba653308',
    messagingSenderId: '873539215769',
    projectId: 'aswack-86a20',
    storageBucket: 'aswack-86a20.appspot.com',
    iosBundleId: 'com.example.zaroooriUser',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAyuO3vNlf4uYoDHSGxKS3Pre1ShqZ6bhI',
    appId: '1:873539215769:web:9ae43d59aa397c37653308',
    messagingSenderId: '873539215769',
    projectId: 'aswack-86a20',
    authDomain: 'aswack-86a20.firebaseapp.com',
    storageBucket: 'aswack-86a20.appspot.com',
    measurementId: 'G-KZVWX9NMQE',
  );
}
